Laboratorio10/Models/PlanetaModel.cs
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace Laboratorio10.Models
{
    public class PlanetaModel
    {
        public int id { get; set; }

        [Required(ErrorMessage = "Es necesario que le indique el nombre del planeta")]
        [Display(Name = "Ingrese el nombre del planeta")]
        public string nombre { get; set; }

        [Required(ErrorMessage = "Es necesario que indique el tipo de planeta")]
        [Display(Name = "Seleccione el tipo de planeta")]
        public string tipo { get; set; }

        [Required(ErrorMessage = "Es necesario que ingrese el número de anillos")]
        [Display(Name = "Ingrese el número de anillos del planeta")]
        [RegularExpression("^[0-9]*$", ErrorMessage ="Debe ingresar números")]
        public int numeroAnillos { get; set; }

        [Required(ErrorMessage = "Debe agregar un archivo (imagen, pdf, etc...)")]
        [Display(Name = "Ingrese el archivo con los detalles del planeta")]
        public HttpPostedFileBase archivo { get; set; }

        public string tipoArchivo { get; set; }
    }
}

Laboratorio10/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Laboratorio10.Controllers {
    public class HomeController : Controller {
        public ActionResult Index() {
            return View("Index");
        }

        public ActionResult About() {
            ViewBag.Message = "Your application description page.";

            return View("About");
        }

        public ActionResult Contact() {
            ViewBag.Message = "Your contact page.";
            ViewBag.ValorParaTest = 1;
            return View("Contact");
        }
    }
}

Laboratorio10/Controllers/PlanetasController.cs
using Laboratorio10.Models;
using Laboratorio10.Handlers;
using System.Web.Mvc;
using System;

namespace Laboratorio10.Controllers
{
    public class PlanetasController : Controller
    {
        public PlanetasHandler accesoDatos { get; set; }

        public PlanetasController() {
            accesoDatos = new PlanetasHandler();
        }

        public PlanetasController(PlanetasHandler planetaHandler) {
            accesoDatos = planetaHandler;
        }


        public ActionResult listadoDePlanetas()
        {
            
            ViewBag.planetas = accesoDatos.obtenerTodosLosPlanetas();
            return View();
        }

        public ActionResult crearPlaneta()
        {
            return View("crearPlaneta");
        }

        [HttpPost]
        public ActionResult crearPlaneta(PlanetaModel planeta)
        {
            ViewBag.ExitoAlCrear = false;
            try
            {
                if (ModelState.IsValid)
                {
                    ViewBag.ExitoAlCrear = accesoDatos.crearPlaneta(planeta);
                    if (ViewBag.ExitoAlCrear)
                    {
                        ViewBag.Message = "El planeta " + planeta.nombre + " fue creado con éxito :)";
                        ModelState.Clear();
                    }
                }
                return View();
            }
            catch
            {
                ViewBag.Message = "Algo salió mal y no fue posible crear el planeta :(";
                return View();
            }
        }

        [HttpGet]
        public ActionResult editarPlaneta(int ? identificador)
        {
            ActionResult vista;
            try
            {
                PlanetaModel planetaModificar = accesoDatos.obtenerTodosLosPlanetas().Find(smodel => smodel.id == identificador);
                if (planetaModificar == null)
                {
                    vista = RedirectToAction("listadoDePlanetas");
                }
                else
                {
                    vista = View(planetaModificar);
                }
            }
            catch
            {
                vista = RedirectToAction("listadoDePlanetas");
            }
            return vista;
        }

        [HttpPost]
        public ActionResult editarPlaneta(PlanetaModel planeta)
        {
            try
            {
                accesoDatos.modificarPlaneta(planeta);
                return RedirectToAction("listadoDePlanetas");
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public FileResult accederArchivo(int identificador)
        {
            try
            {
                var tupla = accesoDatos.descargarContenido(identificador);
                FileResult file = File(tupla.Item1, tupla.Item2);
                return file;
            }
            catch
            {
                return null;
            }
        }
    }
}

Laboratorio10/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Laboratorio10/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Laboratorio10/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Laboratorio10/Views/Planetas/crearPlaneta.cshtml
@model Laboratorio10.Models.PlanetaModel
@{ 
    ViewBag.Title = "Crear Planeta";
    List<SelectListItem> tiposPlanetas = new List<SelectListItem>() {
        new SelectListItem{ Text = "Rocoso" },
        new SelectListItem{ Text = "Gaseoso"},
        new SelectListItem{ Text = "Enano"}
    };
}

<html>
<head>

</head>

<body>
    @if (ViewBag.Message != null)
    {
        if (ViewBag.ExitoAlCrear)
        {
            <div class="alert-success">
                <h3>@ViewBag.Message</h3>
            </div>
        }
        else
        {
            <div class="alert-danger">
                <h3>@ViewBag.Message</h3>
            </div>
        }
    }

    @using (Html.BeginForm("crearPlaneta", "Planetas", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <h1>Formulario de creación de planetas</h1>

        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => model.nombre)
                @Html.TextAreaFor(model => model.nombre, new { style = "width: vw; height: auto;", @class = "form-control", @rows = "5" })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.tipo)
                @Html.DropDownListFor(model => model.tipo, tiposPlanetas, "-Sin selección-", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.tipo, "", new { @class = "text-danger"})
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.archivo)
                @Html.TextBoxFor(model => model.archivo, new { type = "file", @class = "btn btn alert-info"})
                @Html.ValidationMessageFor(model => model.archivo, "", new { @class = "text-danger"})
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.numeroAnillos)
                @Html.TextBoxFor(model => model.numeroAnillos, "", new { @class = "form-control"})
                @Html.ValidationMessageFor(model => model.numeroAnillos, "", new { @class = "text-danger"})
            </div>

            <input type="submit" class="btn btn-success" value="Crear" />
        </div>
    }
</body>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
</html>

Laboratorio10/Views/Planetas/editarPlaneta.cshtml
@model Laboratorio10.Models.PlanetaModel
@{
    ViewBag.Title = "Editar Planeta";
    List<SelectListItem> tiposPlanetas = new List<SelectListItem>() {
        new SelectListItem{ Text = "Rocoso" },
        new SelectListItem{ Text = "Gaseoso"},
        new SelectListItem{ Text = "Enano"}
    };
}

<html>
<head>

</head>

<body>
    @using (Html.BeginForm("editarPlaneta", "Planetas", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <h1>Formulario para editar planetas</h1>

        @Html.HiddenFor(model=>model.id)

        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => model.nombre)
                @Html.TextBoxFor(model => model.nombre, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.tipo)
                @Html.DropDownListFor(model => model.tipo, tiposPlanetas, "-Sin selección-", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.tipo, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.archivo)
                @Html.TextBoxFor(model => model.archivo, new { type = "file", @class = "btn btn alert-info" })
                @Html.ValidationMessageFor(model => model.archivo, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.numeroAnillos)
                @Html.TextBoxFor(model => model.numeroAnillos, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.numeroAnillos, "", new { @class = "text-danger" })
            </div>

            <input type="submit" class="btn btn-success" value="Editar" />
        </div>
    }
</body>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
</html>

Laboratorio10/Views/Planetas/listadoDePlanetas.cshtml
@{
    ViewBag.Title = "Planetas";
}
<!DOCTYPE html>
<html>
<head>
    <title>Planetas</title>
    <meta charset="utf-8" />
</head>
<body>
    <h1>Listado de planetas</h1>




    @foreach (var planeta in @ViewBag.planetas)
    {
        <hr />
        <h2>Ficha de planeta: @planeta.id</h2>
        <p>Nombre: @planeta.nombre</p>
        <p>Tipo: @planeta.tipo</p>
        <p>Numero de anillos: @planeta.numeroAnillos</p>

        @Html.ActionLink("Modificar información", "editarPlaneta",
                      new { identificador = planeta.id },
                      new
                      {
                          @class = "btn btn alert-info",
                          @onclick = "return confirm('¿Quiere modificar este planeta?');"
                      }
        );
        @Html.ActionLink("Ver Contenido Digital", "accederArchivo",
                      new { identificador = planeta.id },
                      new
                      {
                          @class = "btn btn-success",
                      }
        );
        <hr />
    }
</body>
</html>

Laboratorio10/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Listado de Planetas", "listadoDePlanetas", "Planetas")</li>
                    <li>@Html.ActionLink("Crear nuevos planetas", "crearPlaneta", "Planetas")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>